language: python
python:
    - 2.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libinklevel5
install:
    - pip install --upgrade -r dev-requirements.txt
script:
    - py.test
